<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api\Data;

use Magento\Framework\ObjectManagerInterface;

/**
 * Autogenerated description for CustomerProductReviewRequest class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 * @SuppressWarnings(PHPMD.CyclomaticComplexity)
 * @SuppressWarnings(PHPMD.UnusedPrivateField)
 * @SuppressWarnings(PHPMD.NPathComplexity)
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
final class CustomerProductReviewRequestArrayMapper
{
    /**
     * @var mixed
     */
    private $data;

    /**
     * @var ObjectManagerInterface
     */
    private $objectManager;

    public function __construct(ObjectManagerInterface $objectManager)
    {
        $this->objectManager = $objectManager;
    }

    /**
    * Convert the DTO to the array with the data
    *
    * @param CustomerProductReviewRequest $dto
    * @return array
    */
    public function convertToArray(CustomerProductReviewRequest $dto)
    {
        $result = [];
        $result["customer_id"] = $dto->getCustomerId();
        $result["store"] = $dto->getStore();
        if ($dto->getPagination() !== null) {
            $result["pagination"] = $this->objectManager->get(\Magento\ReviewsStorefrontApi\Api\Data\PaginationRequestArrayMapper::class)
                ->convertToArray($dto->getPagination());
        }
        return $result;
    }
}
