<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api\Data;

/**
 * Autogenerated description for PaginationResponse interface
 *
 * @SuppressWarnings(PHPMD.BooleanGetMethodName)
 */
interface PaginationResponseInterface
{
    /**
     * Autogenerated description for getPageSize() interface method
     *
     * @return int
     */
    public function getPageSize(): int;

    /**
     * Autogenerated description for setPageSize() interface method
     *
     * @param int $value
     * @return void
     */
    public function setPageSize(int $value): void;

    /**
     * Autogenerated description for getCursor() interface method
     *
     * @return int
     */
    public function getCursor(): int;

    /**
     * Autogenerated description for setCursor() interface method
     *
     * @param int $value
     * @return void
     */
    public function setCursor(int $value): void;
}
