<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api\Data;

/**
 * Autogenerated description for PaginationRequest class
 *
 * phpcs:disable Magento2.PHP.FinalImplementation
 * @SuppressWarnings(PHPMD)
 * @SuppressWarnings(PHPCPD)
 */
final class PaginationRequest implements PaginationRequestInterface
{

    /**
     * @var int
     */
    private $size;

    /**
     * @var int
     */
    private $cursor;
    
    /**
     * @inheritdoc
     *
     * @return int
     */
    public function getSize(): int
    {
        return (int) $this->size;
    }
    
    /**
     * @inheritdoc
     *
     * @param int $value
     * @return void
     */
    public function setSize(int $value): void
    {
        $this->size = $value;
    }
    
    /**
     * @inheritdoc
     *
     * @return int
     */
    public function getCursor(): int
    {
        return (int) $this->cursor;
    }
    
    /**
     * @inheritdoc
     *
     * @param int $value
     * @return void
     */
    public function setCursor(int $value): void
    {
        $this->cursor = $value;
    }
}
