<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews/reviews.proto

namespace Magento\ReviewsStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.reviewsStorefrontApi.proto.ProductReviewResponse</code>
 */
class ProductReviewResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.ReadReview items = 1;</code>
     */
    private $items;
    /**
     * Generated from protobuf field <code>.magento.reviewsStorefrontApi.proto.PaginationResponse pagination = 2;</code>
     */
    protected $pagination = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Magento\ReviewsStorefrontApi\Proto\ReadReview[]|\Google\Protobuf\Internal\RepeatedField $items
     *     @type \Magento\ReviewsStorefrontApi\Proto\PaginationResponse $pagination
     * }
     */
    public function __construct($data = null)
    {
        \Magento\ReviewsStorefrontApi\Metadata\Reviews::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.ReadReview items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.ReadReview items = 1;</code>
     * @param \Magento\ReviewsStorefrontApi\Proto\ReadReview[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\ReviewsStorefrontApi\Proto\ReadReview::class);
        $this->items = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.magento.reviewsStorefrontApi.proto.PaginationResponse pagination = 2;</code>
     * @return \Magento\ReviewsStorefrontApi\Proto\PaginationResponse
     */
    public function getPagination()
    {
        return $this->pagination;
    }

    /**
     * Generated from protobuf field <code>.magento.reviewsStorefrontApi.proto.PaginationResponse pagination = 2;</code>
     * @param \Magento\ReviewsStorefrontApi\Proto\PaginationResponse $var
     * @return $this
     */
    public function setPagination($var)
    {
        GPBUtil::checkMessage($var, \Magento\ReviewsStorefrontApi\Proto\PaginationResponse::class);
        $this->pagination = $var;

        return $this;
    }
}
