<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reviews/reviews.proto

namespace Magento\ReviewsStorefrontApi\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>magento.reviewsStorefrontApi.proto.RatingMetadata</code>
 */
class RatingMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     * Base64 encoded rating ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * The label assigned to an aspect of a product that is being rated, such as quality or price
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * List of product review ratings
     *
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.RatingValue values = 3;</code>
     */
    private $values;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *           Base64 encoded rating ID
     *     @type string $name
     *           The label assigned to an aspect of a product that is being rated, such as quality or price
     *     @type \Magento\ReviewsStorefrontApi\Proto\RatingValue[]|\Google\Protobuf\Internal\RepeatedField $values
     *           List of product review ratings
     * }
     */
    public function __construct($data = null)
    {
        \Magento\ReviewsStorefrontApi\Metadata\Reviews::initOnce();
        parent::__construct($data);
    }

    /**
     * Base64 encoded rating ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Base64 encoded rating ID
     *
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, true);
        $this->id = $var;

        return $this;
    }

    /**
     * The label assigned to an aspect of a product that is being rated, such as quality or price
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The label assigned to an aspect of a product that is being rated, such as quality or price
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, true);
        $this->name = $var;

        return $this;
    }

    /**
     * List of product review ratings
     *
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.RatingValue values = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValues()
    {
        return $this->values;
    }

    /**
     * List of product review ratings
     *
     * Generated from protobuf field <code>repeated .magento.reviewsStorefrontApi.proto.RatingValue values = 3;</code>
     * @param \Magento\ReviewsStorefrontApi\Proto\RatingValue[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValues($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Magento\ReviewsStorefrontApi\Proto\RatingValue::class);
        $this->values = $arr;

        return $this;
    }
}
