<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api;

use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataResponseInterface;

/**
 * Autogenerated description for InMemoryRatingsMetadata class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class InMemoryRatingsMetadata implements RatingsMetadataInterface
{
    /**
     * @var RatingsMetadataServerInterface
     */
    private $service;

    /**
     * @param RatingsMetadataServerInterface $service
     */
    public function __construct(
        RatingsMetadataServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for importRatingsMetadata in memory client service method
     *
     * @param ImportRatingsMetadataRequestInterface $request
     * @return ImportRatingsMetadataResponseInterface
     */
    public function importRatingsMetadata(ImportRatingsMetadataRequestInterface $request): ImportRatingsMetadataResponseInterface
    {
        return $this->service->importRatingsMetadata($request);
    }

    /**
     * Autogenerated description for deleteRatingsMetadata in memory client service method
     *
     * @param DeleteRatingsMetadataRequestInterface $request
     * @return DeleteRatingsMetadataResponseInterface
     */
    public function deleteRatingsMetadata(DeleteRatingsMetadataRequestInterface $request): DeleteRatingsMetadataResponseInterface
    {
        return $this->service->deleteRatingsMetadata($request);
    }

    /**
     * Autogenerated description for getRatingsMetadata in memory client service method
     *
     * @param RatingsMetadataRequestInterface $request
     * @return RatingsMetadataResponseInterface
     */
    public function getRatingsMetadata(RatingsMetadataRequestInterface $request): RatingsMetadataResponseInterface
    {
        return $this->service->getRatingsMetadata($request);
    }
}
