<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api;

use \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\CustomerProductReviewRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountResponseInterface;

/**
 * Autogenerated description for InMemoryProductReviews class
 *
 * @SuppressWarnings(PHPMD.CouplingBetweenObjects)
 */
class InMemoryProductReviews implements ProductReviewsInterface
{
    /**
     * @var ProductReviewsServerInterface
     */
    private $service;

    /**
     * @param ProductReviewsServerInterface $service
     */
    public function __construct(
        ProductReviewsServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for importProductReviews in memory client service method
     *
     * @param ImportReviewsRequestInterface $request
     * @return ImportReviewsResponseInterface
     */
    public function importProductReviews(ImportReviewsRequestInterface $request): ImportReviewsResponseInterface
    {
        return $this->service->importProductReviews($request);
    }

    /**
     * Autogenerated description for deleteProductReviews in memory client service method
     *
     * @param DeleteReviewsRequestInterface $request
     * @return DeleteReviewsResponseInterface
     */
    public function deleteProductReviews(DeleteReviewsRequestInterface $request): DeleteReviewsResponseInterface
    {
        return $this->service->deleteProductReviews($request);
    }

    /**
     * Autogenerated description for getProductReviews in memory client service method
     *
     * @param ProductReviewRequestInterface $request
     * @return ProductReviewResponseInterface
     */
    public function getProductReviews(ProductReviewRequestInterface $request): ProductReviewResponseInterface
    {
        return $this->service->getProductReviews($request);
    }

    /**
     * Autogenerated description for getCustomerProductReviews in memory client service method
     *
     * @param CustomerProductReviewRequestInterface $request
     * @return ProductReviewResponseInterface
     */
    public function getCustomerProductReviews(CustomerProductReviewRequestInterface $request): ProductReviewResponseInterface
    {
        return $this->service->getCustomerProductReviews($request);
    }

    /**
     * Autogenerated description for getProductReviewCount in memory client service method
     *
     * @param ProductReviewCountRequestInterface $request
     * @return ProductReviewCountResponseInterface
     */
    public function getProductReviewCount(ProductReviewCountRequestInterface $request): ProductReviewCountResponseInterface
    {
        return $this->service->getProductReviewCount($request);
    }
}
