<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api;

use \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\CustomerProductReviewRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountResponseInterface;
use \Magento\ReviewsStorefrontApi\Proto\ImportReviewsRequest;
use \Magento\ReviewsStorefrontApi\Proto\ImportReviewsResponse;
use \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsRequest;
use \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsResponse;
use \Magento\ReviewsStorefrontApi\Proto\ProductReviewRequest;
use \Magento\ReviewsStorefrontApi\Proto\ProductReviewResponse;
use \Magento\ReviewsStorefrontApi\Proto\CustomerProductReviewRequest;
use \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountRequest;
use \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountResponse;
use \Magento\ReviewsStorefrontApi\Proto\ProductReviewsClient;

/**
 * Autogenerated description for ProductReviewsProxyServer class
 *
 * @SuppressWarnings(PHPMD)
 */
class ProductReviewsProxyServer implements \Magento\ReviewsStorefrontApi\Proto\ProductReviewsInterface
{
    /**
     * @var ProductReviewsServerInterface
     */
    private $service;

    /**
     * @param ProductReviewsServerInterface $service
     */
    public function __construct(
        ProductReviewsServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for importProductReviews method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ImportReviewsRequest $in
     * @return ImportReviewsResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function importProductReviews(\Spiral\GRPC\ContextInterface $ctx, ImportReviewsRequest $in): ImportReviewsResponse
    {
        try {
            $magentoDtoRequest = $this->importProductReviewsFromProto($in);
            $magentoDtoResponse = $this->service->importProductReviews($magentoDtoRequest);
            return $this->importProductReviewsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for importProductReviews method
     *
     * @param ImportReviewsRequest $value
     * @return ImportReviewsRequestInterface
     */
    private function importProductReviewsFromProto(ImportReviewsRequest $value): ImportReviewsRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\ImportReviewsRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\ImportReviewsRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsRequest();
            $res = [];
            foreach ($value->getReviews() as $item1) {
                // convert data from \Magento\ReviewsStorefrontApi\Proto\ImportReview
                // to \Magento\ReviewsStorefrontApi\Api\Data\ImportReview
                /** @var \Magento\ReviewsStorefrontApi\Proto\ImportReview $item1 **/
                $p = function () use ($item1) {
                    $r = new \Magento\ReviewsStorefrontApi\Api\Data\ImportReview();
                    $r->setId($item1->getId());
                    $r->setProductId($item1->getProductId());
                    $r->setTitle($item1->getTitle());
                    $r->setNickname($item1->getNickname());
                    $r->setText($item1->getText());
                    $r->setCustomerId($item1->getCustomerId());
                    $values = [];
                    foreach ($item1->getVisibility() as $newValue) {
                        $values[] = $newValue;
                    }
                    $r->setVisibility($values);
                    $res = [];
                    foreach ($item1->getRatings() as $item9) {
                        // convert data from \Magento\ReviewsStorefrontApi\Proto\Rating
                        // to \Magento\ReviewsStorefrontApi\Api\Data\Rating
                        /** @var \Magento\ReviewsStorefrontApi\Proto\Rating $item9 **/
                        $p = function () use ($item9) {
                            $r = new \Magento\ReviewsStorefrontApi\Api\Data\Rating();
                            $r->setRatingId($item9->getRatingId());
                            $r->setValue($item9->getValue());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setRatings($res);
                    return $r;
                };
                $out = $p();
                $res[] = $out;
            }
            $r->setReviews($res);
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for importProductReviews method
     *
     * @param ImportReviewsResponseInterface $value
     * @return ImportReviewsResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function importProductReviewsToProto(ImportReviewsResponseInterface $value): ImportReviewsResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsResponse
        // to \Magento\ReviewsStorefrontApi\Proto\ImportReviewsResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\ImportReviewsResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\ImportReviewsResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for deleteProductReviews method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param DeleteReviewsRequest $in
     * @return DeleteReviewsResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function deleteProductReviews(\Spiral\GRPC\ContextInterface $ctx, DeleteReviewsRequest $in): DeleteReviewsResponse
    {
        try {
            $magentoDtoRequest = $this->deleteProductReviewsFromProto($in);
            $magentoDtoResponse = $this->service->deleteProductReviews($magentoDtoRequest);
            return $this->deleteProductReviewsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for deleteProductReviews method
     *
     * @param DeleteReviewsRequest $value
     * @return DeleteReviewsRequestInterface
     */
    private function deleteProductReviewsFromProto(DeleteReviewsRequest $value): DeleteReviewsRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsRequest();
            $values = [];
            foreach ($value->getReviewIds() as $newValue) {
                $values[] = $newValue;
            }
            $r->setReviewIds($values);
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for deleteProductReviews method
     *
     * @param DeleteReviewsResponseInterface $value
     * @return DeleteReviewsResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function deleteProductReviewsToProto(DeleteReviewsResponseInterface $value): DeleteReviewsResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsResponse
        // to \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\DeleteReviewsResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\DeleteReviewsResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for getProductReviews method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ProductReviewRequest $in
     * @return ProductReviewResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function getProductReviews(\Spiral\GRPC\ContextInterface $ctx, ProductReviewRequest $in): ProductReviewResponse
    {
        try {
            $magentoDtoRequest = $this->getProductReviewsFromProto($in);
            $magentoDtoResponse = $this->service->getProductReviews($magentoDtoRequest);
            return $this->getProductReviewsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getProductReviews method
     *
     * @param ProductReviewRequest $value
     * @return ProductReviewRequestInterface
     */
    private function getProductReviewsFromProto(ProductReviewRequest $value): ProductReviewRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\ProductReviewRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\ProductReviewRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewRequest();
            $r->setProductId($value->getProductId());
            $r->setStore($value->getStore());
            $prop3 = $value->getPagination();
            if ($prop3 !== null) {
                // convert data from \Magento\ReviewsStorefrontApi\Proto\PaginationRequest
                // to \Magento\ReviewsStorefrontApi\Api\Data\PaginationRequest
                /** @var \Magento\ReviewsStorefrontApi\Proto\PaginationRequest $prop3 **/
                $p = function () use ($prop3) {
                    $r = new \Magento\ReviewsStorefrontApi\Api\Data\PaginationRequest();
                    $r->setSize($prop3->getSize());
                    $r->setCursor($prop3->getCursor());
                    return $r;
                };
                $out = $p();
                $r->setPagination($out);
            }
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getProductReviews method
     *
     * @param ProductReviewResponseInterface $value
     * @return ProductReviewResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getProductReviewsToProto(ProductReviewResponseInterface $value): ProductReviewResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponse
        // to \Magento\ReviewsStorefrontApi\Proto\ProductReviewResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\ProductReviewResponse();
            $res = [];
            foreach ($value->getItems() as $item1) {
                // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ReadReview
                // to \Magento\ReviewsStorefrontApi\Proto\ReadReview
                /** @var \Magento\ReviewsStorefrontApi\Api\Data\ReadReview $item1 **/
                $p = function () use ($item1) {
                    $r = new \Magento\ReviewsStorefrontApi\Proto\ReadReview();
                    $r->setId($item1->getId());
                    $r->setProductId($item1->getProductId());
                    $r->setTitle($item1->getTitle());
                    $r->setNickname($item1->getNickname());
                    $r->setText($item1->getText());
                    $res = [];
                    foreach ($item1->getRatings() as $item7) {
                        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\Rating
                        // to \Magento\ReviewsStorefrontApi\Proto\Rating
                        /** @var \Magento\ReviewsStorefrontApi\Api\Data\Rating $item7 **/
                        $p = function () use ($item7) {
                            $r = new \Magento\ReviewsStorefrontApi\Proto\Rating();
                            $r->setRatingId($item7->getRatingId());
                            $r->setValue($item7->getValue());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setRatings($res);
                    return $r;
                };
                $proto = $p();
                $res[] = $proto;
            }
            $r->setItems($res);
            $prop2 = $value->getPagination();
            if ($prop2 !== null) {
                // convert data from \Magento\ReviewsStorefrontApi\Api\Data\PaginationResponse
                // to \Magento\ReviewsStorefrontApi\Proto\PaginationResponse
                /** @var \Magento\ReviewsStorefrontApi\Api\Data\PaginationResponse $prop2 **/
                $p = function () use ($prop2) {
                    $r = new \Magento\ReviewsStorefrontApi\Proto\PaginationResponse();
                    $r->setPageSize($prop2->getPageSize());
                    $r->setCursor($prop2->getCursor());
                    return $r;
                };
                $proto = $p();
                $r->setPagination($proto);
            }
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for getCustomerProductReviews method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param CustomerProductReviewRequest $in
     * @return ProductReviewResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function getCustomerProductReviews(\Spiral\GRPC\ContextInterface $ctx, CustomerProductReviewRequest $in): ProductReviewResponse
    {
        try {
            $magentoDtoRequest = $this->getCustomerProductReviewsFromProto($in);
            $magentoDtoResponse = $this->service->getCustomerProductReviews($magentoDtoRequest);
            return $this->getCustomerProductReviewsToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getCustomerProductReviews method
     *
     * @param CustomerProductReviewRequest $value
     * @return CustomerProductReviewRequestInterface
     */
    private function getCustomerProductReviewsFromProto(CustomerProductReviewRequest $value): CustomerProductReviewRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\CustomerProductReviewRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\CustomerProductReviewRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\CustomerProductReviewRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\CustomerProductReviewRequest();
            $r->setCustomerId($value->getCustomerId());
            $r->setStore($value->getStore());
            $prop3 = $value->getPagination();
            if ($prop3 !== null) {
                // convert data from \Magento\ReviewsStorefrontApi\Proto\PaginationRequest
                // to \Magento\ReviewsStorefrontApi\Api\Data\PaginationRequest
                /** @var \Magento\ReviewsStorefrontApi\Proto\PaginationRequest $prop3 **/
                $p = function () use ($prop3) {
                    $r = new \Magento\ReviewsStorefrontApi\Api\Data\PaginationRequest();
                    $r->setSize($prop3->getSize());
                    $r->setCursor($prop3->getCursor());
                    return $r;
                };
                $out = $p();
                $r->setPagination($out);
            }
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getCustomerProductReviews method
     *
     * @param ProductReviewResponseInterface $value
     * @return ProductReviewResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getCustomerProductReviewsToProto(ProductReviewResponseInterface $value): ProductReviewResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponse
        // to \Magento\ReviewsStorefrontApi\Proto\ProductReviewResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\ProductReviewResponse();
            $res = [];
            foreach ($value->getItems() as $item1) {
                // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ReadReview
                // to \Magento\ReviewsStorefrontApi\Proto\ReadReview
                /** @var \Magento\ReviewsStorefrontApi\Api\Data\ReadReview $item1 **/
                $p = function () use ($item1) {
                    $r = new \Magento\ReviewsStorefrontApi\Proto\ReadReview();
                    $r->setId($item1->getId());
                    $r->setProductId($item1->getProductId());
                    $r->setTitle($item1->getTitle());
                    $r->setNickname($item1->getNickname());
                    $r->setText($item1->getText());
                    $res = [];
                    foreach ($item1->getRatings() as $item7) {
                        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\Rating
                        // to \Magento\ReviewsStorefrontApi\Proto\Rating
                        /** @var \Magento\ReviewsStorefrontApi\Api\Data\Rating $item7 **/
                        $p = function () use ($item7) {
                            $r = new \Magento\ReviewsStorefrontApi\Proto\Rating();
                            $r->setRatingId($item7->getRatingId());
                            $r->setValue($item7->getValue());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setRatings($res);
                    return $r;
                };
                $proto = $p();
                $res[] = $proto;
            }
            $r->setItems($res);
            $prop2 = $value->getPagination();
            if ($prop2 !== null) {
                // convert data from \Magento\ReviewsStorefrontApi\Api\Data\PaginationResponse
                // to \Magento\ReviewsStorefrontApi\Proto\PaginationResponse
                /** @var \Magento\ReviewsStorefrontApi\Api\Data\PaginationResponse $prop2 **/
                $p = function () use ($prop2) {
                    $r = new \Magento\ReviewsStorefrontApi\Proto\PaginationResponse();
                    $r->setPageSize($prop2->getPageSize());
                    $r->setCursor($prop2->getCursor());
                    return $r;
                };
                $proto = $p();
                $r->setPagination($proto);
            }
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for getProductReviewCount method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ProductReviewCountRequest $in
     * @return ProductReviewCountResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function getProductReviewCount(\Spiral\GRPC\ContextInterface $ctx, ProductReviewCountRequest $in): ProductReviewCountResponse
    {
        try {
            $magentoDtoRequest = $this->getProductReviewCountFromProto($in);
            $magentoDtoResponse = $this->service->getProductReviewCount($magentoDtoRequest);
            return $this->getProductReviewCountToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getProductReviewCount method
     *
     * @param ProductReviewCountRequest $value
     * @return ProductReviewCountRequestInterface
     */
    private function getProductReviewCountFromProto(ProductReviewCountRequest $value): ProductReviewCountRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountRequest();
            $r->setProductId($value->getProductId());
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getProductReviewCount method
     *
     * @param ProductReviewCountResponseInterface $value
     * @return ProductReviewCountResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getProductReviewCountToProto(ProductReviewCountResponseInterface $value): ProductReviewCountResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountResponse
        // to \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\ProductReviewCountResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\ProductReviewCountResponse();
            $r->setReviewCount($value->getReviewCount());
            return $r;
        };
        $proto = $p();

        return $proto;
    }
}
