<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api;

use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataRequest;
use \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataResponse;
use \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataRequest;
use \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataResponse;
use \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataRequest;
use \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataResponse;
use \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataClient;

/**
 * Autogenerated description for RatingsMetadataProxyServer class
 *
 * @SuppressWarnings(PHPMD)
 */
class RatingsMetadataProxyServer implements \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataInterface
{
    /**
     * @var RatingsMetadataServerInterface
     */
    private $service;

    /**
     * @param RatingsMetadataServerInterface $service
     */
    public function __construct(
        RatingsMetadataServerInterface $service
    ) {
        $this->service = $service;
    }

    /**
     * Autogenerated description for importRatingsMetadata method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param ImportRatingsMetadataRequest $in
     * @return ImportRatingsMetadataResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function importRatingsMetadata(\Spiral\GRPC\ContextInterface $ctx, ImportRatingsMetadataRequest $in): ImportRatingsMetadataResponse
    {
        try {
            $magentoDtoRequest = $this->importRatingsMetadataFromProto($in);
            $magentoDtoResponse = $this->service->importRatingsMetadata($magentoDtoRequest);
            return $this->importRatingsMetadataToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for importRatingsMetadata method
     *
     * @param ImportRatingsMetadataRequest $value
     * @return ImportRatingsMetadataRequestInterface
     */
    private function importRatingsMetadataFromProto(ImportRatingsMetadataRequest $value): ImportRatingsMetadataRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataRequest();
            $res = [];
            foreach ($value->getMetadata() as $item1) {
                // convert data from \Magento\ReviewsStorefrontApi\Proto\RatingMetadata
                // to \Magento\ReviewsStorefrontApi\Api\Data\RatingMetadata
                /** @var \Magento\ReviewsStorefrontApi\Proto\RatingMetadata $item1 **/
                $p = function () use ($item1) {
                    $r = new \Magento\ReviewsStorefrontApi\Api\Data\RatingMetadata();
                    $r->setId($item1->getId());
                    $r->setName($item1->getName());
                    $res = [];
                    foreach ($item1->getValues() as $item4) {
                        // convert data from \Magento\ReviewsStorefrontApi\Proto\RatingValue
                        // to \Magento\ReviewsStorefrontApi\Api\Data\RatingValue
                        /** @var \Magento\ReviewsStorefrontApi\Proto\RatingValue $item4 **/
                        $p = function () use ($item4) {
                            $r = new \Magento\ReviewsStorefrontApi\Api\Data\RatingValue();
                            $r->setValueId($item4->getValueId());
                            $r->setValue($item4->getValue());
                            $r->setPosition($item4->getPosition());
                            return $r;
                        };
                        $out = $p();
                        $res[] = $out;
                    }
                    $r->setValues($res);
                    return $r;
                };
                $out = $p();
                $res[] = $out;
            }
            $r->setMetadata($res);
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for importRatingsMetadata method
     *
     * @param ImportRatingsMetadataResponseInterface $value
     * @return ImportRatingsMetadataResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function importRatingsMetadataToProto(ImportRatingsMetadataResponseInterface $value): ImportRatingsMetadataResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataResponse
        // to \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\ImportRatingsMetadataResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for deleteRatingsMetadata method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param DeleteRatingsMetadataRequest $in
     * @return DeleteRatingsMetadataResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function deleteRatingsMetadata(\Spiral\GRPC\ContextInterface $ctx, DeleteRatingsMetadataRequest $in): DeleteRatingsMetadataResponse
    {
        try {
            $magentoDtoRequest = $this->deleteRatingsMetadataFromProto($in);
            $magentoDtoResponse = $this->service->deleteRatingsMetadata($magentoDtoRequest);
            return $this->deleteRatingsMetadataToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for deleteRatingsMetadata method
     *
     * @param DeleteRatingsMetadataRequest $value
     * @return DeleteRatingsMetadataRequestInterface
     */
    private function deleteRatingsMetadataFromProto(DeleteRatingsMetadataRequest $value): DeleteRatingsMetadataRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataRequest();
            $values = [];
            foreach ($value->getRatingIds() as $newValue) {
                $values[] = $newValue;
            }
            $r->setRatingIds($values);
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for deleteRatingsMetadata method
     *
     * @param DeleteRatingsMetadataResponseInterface $value
     * @return DeleteRatingsMetadataResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function deleteRatingsMetadataToProto(DeleteRatingsMetadataResponseInterface $value): DeleteRatingsMetadataResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataResponse
        // to \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\DeleteRatingsMetadataResponse();
            $r->setStatus($value->getStatus());
            $r->setMessage($value->getMessage());
            return $r;
        };
        $proto = $p();

        return $proto;
    }

    /**
     * Autogenerated description for getRatingsMetadata method
     *
     * @param \Spiral\GRPC\ContextInterface $ctx
     * @param RatingsMetadataRequest $in
     * @return RatingsMetadataResponse
     * @SuppressWarnings(PHPMD.UnusedFormalParameter)
     */
    public function getRatingsMetadata(\Spiral\GRPC\ContextInterface $ctx, RatingsMetadataRequest $in): RatingsMetadataResponse
    {
        try {
            $magentoDtoRequest = $this->getRatingsMetadataFromProto($in);
            $magentoDtoResponse = $this->service->getRatingsMetadata($magentoDtoRequest);
            return $this->getRatingsMetadataToProto($magentoDtoResponse);
        } catch (\Exception $e) {
            throw new \Spiral\GRPC\Exception\InvokeException(
                $e->getMessage(),
                \Spiral\GRPC\StatusCode::UNKNOWN,
                [],
                $e
            );
        }
    }

    /**
     * Autogenerated description for getRatingsMetadata method
     *
     * @param RatingsMetadataRequest $value
     * @return RatingsMetadataRequestInterface
     */
    private function getRatingsMetadataFromProto(RatingsMetadataRequest $value): RatingsMetadataRequestInterface
    {
        // convert data from \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataRequest
        // to \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataRequest
        /** @var \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataRequest $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataRequest();
            $values = [];
            foreach ($value->getRatingIds() as $newValue) {
                $values[] = $newValue;
            }
            $r->setRatingIds($values);
            $r->setStore($value->getStore());
            return $r;
        };
        $out = $p();

        return $out;
    }

    /**
     * Autogenerated description for getRatingsMetadata method
     *
     * @param RatingsMetadataResponseInterface $value
     * @return RatingsMetadataResponse
     * phpcs:disable Generic.Metrics.NestingLevel.TooHigh
     */
    private function getRatingsMetadataToProto(RatingsMetadataResponseInterface $value): RatingsMetadataResponse
    {
        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataResponse
        // to \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataResponse
        /** @var \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataResponse $value **/
        $p = function () use ($value) {
            $r = new \Magento\ReviewsStorefrontApi\Proto\RatingsMetadataResponse();
            $res = [];
            foreach ($value->getItems() as $item1) {
                // convert data from \Magento\ReviewsStorefrontApi\Api\Data\RatingMetadata
                // to \Magento\ReviewsStorefrontApi\Proto\RatingMetadata
                /** @var \Magento\ReviewsStorefrontApi\Api\Data\RatingMetadata $item1 **/
                $p = function () use ($item1) {
                    $r = new \Magento\ReviewsStorefrontApi\Proto\RatingMetadata();
                    $r->setId($item1->getId());
                    $r->setName($item1->getName());
                    $res = [];
                    foreach ($item1->getValues() as $item4) {
                        // convert data from \Magento\ReviewsStorefrontApi\Api\Data\RatingValue
                        // to \Magento\ReviewsStorefrontApi\Proto\RatingValue
                        /** @var \Magento\ReviewsStorefrontApi\Api\Data\RatingValue $item4 **/
                        $p = function () use ($item4) {
                            $r = new \Magento\ReviewsStorefrontApi\Proto\RatingValue();
                            $r->setValueId($item4->getValueId());
                            $r->setValue($item4->getValue());
                            $r->setPosition($item4->getPosition());
                            return $r;
                        };
                        $proto = $p();
                        $res[] = $proto;
                    }
                    $r->setValues($res);
                    return $r;
                };
                $proto = $p();
                $res[] = $proto;
            }
            $r->setItems($res);
            return $r;
        };
        $proto = $p();

        return $proto;
    }
}
