<?php
# Generated by the Magento PHP proto generator.  DO NOT EDIT!

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

declare(strict_types=1);

namespace Magento\ReviewsStorefrontApi\Api;

use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\ImportRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\DeleteRatingsMetadataResponseInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataRequestInterface;
use \Magento\ReviewsStorefrontApi\Api\Data\RatingsMetadataResponseInterface;

/**
 * Autogenerated description for RatingsMetadataServerInterface interface
 */
interface RatingsMetadataServerInterface
{
    /**
     * Autogenerated description for importRatingsMetadata interface method
     *
     * @param ImportRatingsMetadataRequestInterface $request
     * @return ImportRatingsMetadataResponseInterface
     * @throws \Throwable
     */
    public function importRatingsMetadata(ImportRatingsMetadataRequestInterface $request): ImportRatingsMetadataResponseInterface;

    /**
     * Autogenerated description for deleteRatingsMetadata interface method
     *
     * @param DeleteRatingsMetadataRequestInterface $request
     * @return DeleteRatingsMetadataResponseInterface
     * @throws \Throwable
     */
    public function deleteRatingsMetadata(DeleteRatingsMetadataRequestInterface $request): DeleteRatingsMetadataResponseInterface;

    /**
     * Autogenerated description for getRatingsMetadata interface method
     *
     * @param RatingsMetadataRequestInterface $request
     * @return RatingsMetadataResponseInterface
     * @throws \Throwable
     */
    public function getRatingsMetadata(RatingsMetadataRequestInterface $request): RatingsMetadataResponseInterface;
}
